### PR TITLE
Code change to assign shuffled user and item ids instead of sequential ids.

### PR DESCRIPTION
**Pull request by shashankrajput**
The preprocessing done by P5 leads to item sequences which consist of consecutive integers of the form "a, a+1, a+2, ...". We suspect LLMs like T5 are easily able to identify such integer sequences since they are known to be intelligent enough to do that. Since this is being done for the entire dataset, including the **_test sample_**, predicting the test sample becomes easy since it is simply "max{items seen in sequence so far} + 1" a lot of the times. Please see the attached screenshot below to see these types of sequences in the dataset. Each line represents a user session, and the last item of each sequence is the test sample.

p5

A way to fix this is to assign ids after shuffling instead of sequential. This logic has been implemented in this pull request.

### CODE REVIEW

**Comment by evison** [comment]
1. Number ID is just a label for an item, from the model's perspective, the IDs are just embedding vectors to be learned, and eventually the model needs to use the embedding vectors rather than the numerical meaning of the ID to make recommendations. After model optimization, both the embedding parameters and the model parameters are completely different from the original T5 model, as a result, one cannot say that the model is using T5’s understanding of numbers to do recommendation. 
2. If your suspect is true, then using random ID is unreasonable and one should use sequential numbering even more, because random numbering will assign consecutive numbers to unrelated random items, and thus will force the model to recommend unrelated items just because their IDs are consecutive, which is unfair. In light of this, sequential numbering is a more reasonable choice.

**Comment by JiachengLi1995** [comment]
I think we can test the model in another way:
First, we are still using sequential numbering as mentioned in the paper and the code, but we have a different test set. In the new test set, we select only items whose IDs are smaller than the previous numbers. For example, in the above picture, we use the following sequences:
7 50 51 52 53 54 55 **4**
12 15 98 99 100 101 83 102 103 **28**
We can keep the same training and development set as mentioned in the paper and compare the results to other baselines such as SASRec, BERT4Rec. @shashankrajput @jeykigung @evison  Do you think this is a fair comparison? If so, please have some experiments on this setting, thank you!

If sequential numbering is reasonable, P5 should also have superior results on the new test set compared to other baselines.

**Comment by JiachengLi1995** [comment]
If sequential numbering is reasonable, P5 should also have superior results on the new test set compared to other baselines.

**Comment by JiachengLi1995** [comment]
We can think about the following questions:
1. Should recommenders make predictions based on (or related to) item IDs?
2. Does P5 make predictions based on (or related to) item IDs?

I first assume all of us will think that question 1 is False.
Then, let's discuss question 2:
If question 2 is False, then random IDs are totally reasonable, because P5 doesn't rely on item IDs and it doesn't matter how we number these items.
If question 2 is True, then P5 has a wrong setting (i.e., based on item IDs) because we think question 1 is False.

What if question 1 is True? Do need to study how to number items? I think this is unreasonable.

**Comment by evison** [comment]
The reasoning is based on Shashank's assumption that P5 makes prediction based on LLM's understanding of number sequences. This can be either true or false. If it's false, then P5's prediction is irrelevant to LLM's number semantic; if it's true, then a contradiction can be derived such that random numbering is unreasonable.

**Comment by evison** [comment]
> We can think about the following questions:
> 1. Should recommenders make predictions based on (or related to) item IDs?
> 2. Does P5 make predictions based on (or related to) item IDs?

These are very good questions to consider, thanks for inspiring the discussions. For 1), I actually tend to believe that it's true. In fact, this will become a huge research direction for recommendation foundation models.

**Pull request closed without merging**
